// <auto-generated />
using ConsoleAppNetCoreEf.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppNetCoreEf.Migrations
{
    [DbContext(typeof(PesananContext))]
    partial class PesananContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsoleAppNetCoreEf.Entities.pesananOrang", b =>
                {
                    b.Property<string>("AlamatPesanan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BanyakPesanan")
                        .HasColumnType("int");

                    b.Property<int>("DurasiPesanan")
                        .HasColumnType("int");

                    b.Property<string>("NamaPemesan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelpPemesan")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Orderan");
                });
#pragma warning restore 612, 618
        }
    }
}
